import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Products from '../components/Products/Products'
import Header from '../components/Header/Header'
import About from '../components/About/About'
import Clients from '../components/Clients/Clients'
import Contact from '../components/Contact/Contact'
import Footer from '../components/Footer/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
    <Head>
      <title>Qualimed</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
      <meta name="description" 				content="Servicio de bombas industriales. Taller propio para reparación y reconstrucción de bombas. Presupuestos en 24 horas. Traslados de equipamientos y servicios de emergencia"/>
      <meta name="viewport" 			content="width=device-width, initial-scale=1, maximum-scale=1"/>
      <meta name="keywords" 			content="Servicio de bombas industriales. Taller propio para reparación y reconstrucción de bombas. Presupuestos en 24 horas. Traslados de equipamientos y servicios de emergencia"/>
      <meta name="author" 			content="Qualimed"/>
      <meta property="og:type" 		content="website" />
      <meta property="og:title" 		content="Qualimed" />
      <meta property="og:description" content="Servicio de bombas Industriales" />
      <meta property="og:url" 		content="https://www.bukmasrl.com.ar" />
      <meta property="og:site_name" 	content="Qualimed" />
      <link rel="icon" 		 href="/favicon.ico"/>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
      
    </Head>
    <Header/>
    <div className={styles.hero}><h1>Hero</h1></div>
    <div className={styles.products}><h1>Productos</h1></div>
    <div className={styles.sections}><h1>Secciones</h1></div>
    <div className={styles.branding}><h1>Branding</h1></div>
    <div className={styles.contact}><h1>Contacto</h1></div>
    <div className={styles.footer} ><h1>Footer</h1></div>
    {/* <About/>
    <Clients/>
    <Contact/> */}
    <Footer/>


  </div>
  )
}
